### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by jrob8577**
Creating a PR to offer feedback; this need not be merged (can be closed or added to as you see fit)

### CODE REVIEW

**Comment by jrob8577** [comment]
I opened this to try to help, but not sure where the problem is?

**Comment by pllearns** [comment]
Rachel has an idea, standby. Thanks for checking in :)

**Comment by rachel-ftw** [comment]
ok, we're still stuck.

We're trying to get individual quiz questions to display on the page with their answers. We got all the questions and all the answers piped into the front end and displayed on one page, but we've been struggling for a day on arranging question N and all N's answers to display together.

We tried to adjust the handlebars/front end to display the information correctly. 
We tried to repackage the information in the database.js file to send the information up through the routes in a more usable format for the front end. 
We tried querying the database differently so that we would get the information correctly...

I know we're a half step away, but I can't figure it out (nor can Dev).

check out getAllQuestionsByQuizSession in database.js. All of that file really. 
The data comes out like this
```
[ [ anonymous {
      id: 1,
      question_text: 'What is Eleven\'s favorite food?',
      img_url: 'https://pmctvline2.files.wordpress.com/2016/07/stranger-things-eleven.jpg' },
    anonymous {
      id: 2,
      question_text: 'What is the name of the place where Will and Barb ended up? ',
      img_url: 'http://vignette3.wikia.nocookie.net/strangerthings8338/images/8/8b/TheMonsterEpisode.jpg/revision/latest?cb=20160819171436' },
    anonymous {
      id: 3,
      question_text: 'Where does Stranger Things take place? ',
      img_url: 'http://media.architecturaldigest.com/photos/57a3b7be4cd107bb4fa4c3b7/master/w_806/stranger-things-filming-locations-004.jpg' } ],
  [ anonymous { id: 1, question_id: 1, answer_text: 'Eggos', correct: true },
    anonymous { id: 2, question_id: 1, answer_text: 'Pancakes', correct: false },
    anonymous { id: 3, question_id: 1, answer_text: 'Bacon', correct: false },
    anonymous {
      id: 4,
      question_id: 1,
      answer_text: 'Apple Pie',
      correct: false },
    anonymous {
      id: 5,
      question_id: 1,
      answer_text: 'Hamburger',
      correct: false },
    anonymous {
      id: 6,
      question_id: 2,
      answer_text: 'Purgatory',
      correct: false },
    anonymous {
      id: 7,
      question_id: 2,
      answer_text: 'The Dark Side',
      correct: false },
    anonymous {
      id: 8,
      question_id: 2,
      answer_text: 'The Upside Down',
      correct: true },
    anonymous {
      id: 9,
      question_id: 2,
      answer_text: 'The Entryway',
      correct: false },
    anonymous {
      id: 10,
      question_id: 2,
      answer_text: 'The Mucky Place',
      correct: false },
    anonymous {
      id: 11,
      question_id: 3,
      answer_text: 'Bloomington, IN',
      correct: false },
    anonymous {
      id: 12,
      question_id: 3,
      answer_text: 'Hattonfield, IN',
      correct: false },
    anonymous {
      id: 13,
      question_id: 3,
      answer_text: 'Alberquerque, NM',
      correct: false },
    anonymous {
      id: 14,
      question_id: 3,
      answer_text: 'Hawkins, IN',
      correct: true },
    anonymous {
      id: 15,
      question_id: 3,
      answer_text: 'Oakland, CA',
      correct: false } ] ]
```

we've been trying to get our data to come up like
```
[ { id: 1,
    question_text: 'What is Eleven\'s favorite food?',
    img_url: 'https://pmctvline2.files.wordpress.com/2016/07/stranger-things-eleven.jpg' }
    answers: [[ anonymous { id: 1, question_id: 1, answer_text: 'Eggos', correct: true },
    anonymous { id: 2, question_id: 1, answer_text: 'Pancakes', correct: false },
    anonymous { id: 3, question_id: 1, answer_text: 'Bacon', correct: false },
    anonymous { id: 4, question_id: 1, answer_text: 'Apple Pie', correct: false },
    anonymous { id: 5, question_id: 1, answer_text: 'Hamburger', correct: false }],
    { id: 2,
    question_text: ...
```

are we thinking about this wrong?I have a sneaking suspicion we're making this harder than we need to and some handlebars magic could have fixed this at 9am this morning... :/

**Comment by jrob8577** [comment]
Is this still blocked?

**Comment by pllearns** [comment]
@jrob8577 Update: The site can now display all questions with answers and question images in the correct order on a single page. We need to create radio buttons for answering questions, and continue shaping the page.

**Comment by jrob8577** [comment]
How can I help?

**Comment by pllearns** [comment]
Hey @jrob8577, I assigned you to issues #19 and #15 and made a request for a push in the right direction.

**Comment by pllearns** [comment]
Also, @jrob8577, could you take a look at this request so I can merge?

**Comment by pllearns** [comment]
Hey @rachel-ftw and @jrob8577. We need to push forward to another branch to start scoring. I am asking for forgiveness as I will merge this branch. The master is too far behind to be useful. Thanks for your understanding. :)

**Pull request merged**
